### ISSUE TITLE
Colab link

### ISSUE THREAD

**Issue by Amrutha1101** [Hlestov/QA-Distilbert-finetuning#1]
Hello,
I'm interested to take up this project. Can you provide or attach the colab link too in readme or here and also share the dataset used in the 
PATH = '/content/nlp_test_task_2023/dataset' . Let me know if you would like to share these through any other socials if not possible here  like through mail.

Thanks in advance

**Comment by Hlestov** [comment]
I added a Colab link. The dataset is available on Google Drive and can be downloaded automatically using the !gdown command.
